name: Aliyun Docker Base Image

on:
  workflow_dispatch:
  push:
jobs:
  push_to_registry:
    name: Push Docker image to Aliyun
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses:  docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: hustme
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: jdk
        uses: docker/build-push-action@v6
        with:
          file: ./17/Dockerfile
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/jiangood/jdk:17
          build-args: |
            VERSION=${{ steps.meta.outputs.tag }}
